feat: replace phpmd to phpstan

diff --git a/contrib/pre-commit b/contrib/pre-commit
--- a/contrib/pre-commit
+++ b/contrib/pre-commit
@@ -6,12 +6,9 @@ if [ -z $container ]
         echo "Your container name is not valid. Try put response-json-php-lib on the end of container's name."
 fi
 
-echo "Checking PHP Lint in src..."
-docker exec $container find ./src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l -d display_errors=0
-docker exec $container find ./tests -name "*.php" -print0 | xargs -0 -n1 -P8 php -l -d display_errors=0
-docker exec $container find ./sample -name "*.php" -print0 | xargs -0 -n1 -P8 php -l -d display_errors=0
-if [ $? != 0 ]
-then
+echo "Checking PHP Lint..."
+docker exec -w /var/www/html "$container" composer lint
+if [ $? != 0 ]; then
     echo "Fix the PHP sintax errors before commit."
     exit 1
 fi
@@ -24,17 +21,16 @@ then
     exit 1
 fi
 
-echo "Running PHP Mess Detector..."
-docker exec $container ./vendor/bin/phpmd ./src text phpmd.xml
-docker exec $container ./vendor/bin/phpmd ./sample text phpmd.xml
+echo "Running PHP Stan..."
+docker exec $container ./vendor/bin/phpstan analyse
 if [ $? != 0 ]
 then
-    echo "Fix the PHP Mess Detector errors before commit."
+    echo "Fix the PHP Stan errors before commit."
     exit 1
 fi
 
 echo "Running Unit Tests..."
-docker exec $container phpdbg -qrr vendor/bin/phpunit --configuration phpunit.xml -d memory_limit=1024M
+docker exec $container php -d xdebug.mode=coverage vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage/coverage.xml -d memory_limit=1024M
 if [ $? != 0 ]
 then
     echo "Fix the Unit Tests errors before commit."
@@ -42,7 +38,7 @@ then
 fi
 
 echo "Checking Unit Coverage..."
-php contrib/coverage-checker.php coverage/coverage.xml 100
+docker exec $container php contrib/coverage-checker.php coverage/coverage.xml 100
 
 if [ $? != 0 ]
 then
